#!/usr/bin/env zsh

# Correct path for Mac OS X
path=(/opt/local/bin /opt/local/lib/postgresql/bin /usr/local/texlive/2008/bin/universal-darwin $path)

# Update MANPATH for MacPorts
manpath=(/opt/local/man $manpath)
