#!/usr/bin/env zsh

# Make sure these directories are in PATH.
path=($path /usr/local/bin /usr/local/sbin /usr/games /usr/bin /usr/sbin /bin /sbin)

# Some aliases for Linux
alias vnc="ssvncviewer -escape Alt_L"

# Allow more control keys through in the terminal
if [ -t 1 ]; then
  stty stop undef
  stty start undef
fi
