#!/usr/bin/env zsh

################################################################################
# Set NIX_PATH to use my local channel, if I'm on NixOS.
if [ -n "$NIX_PATH" ]; then
  # NixOS
  NIX_PATH="nixpkgs=$HOME/.nix-defexpr/channels/nixpkgs:$NIX_PATH"
else
  # Make sure these directories are in PATH.
  path=($path /usr/local/bin /usr/local/sbin /usr/games /usr/bin /usr/sbin /bin /sbin)
fi

################################################################################
# NixOS internally knows where to search for man pages.  Help zsh auto
# complete on them.
if [ -d ~/.nix-profile ]; then
  MANPATH=`man -w`
fi

################################################################################
# Some aliases for Linux
alias vnc="ssvncviewer -escape Alt_L"

################################################################################
# Allow more control keys through in the terminal
if [ -t 1 ]; then
  stty stop undef
  stty start undef
fi
