################################################################################
include ../mk/init.mk
include ../mk/files.mk

################################################################################
$(eval $(call PMADE_INSTALL_DOT,dictrc))
$(eval $(call PMADE_INSTALL_DOT,editrc))
$(eval $(call PMADE_INSTALL_DOT,lircrc))
$(eval $(call PMADE_INSTALL_DOT,festivalrc))

################################################################################
$(eval $(call PMADE_INSTALL_FILE,pulse.default.pa,~/.config/pulse/default.pa))
