################################################################################
include ../mk/init.mk
include ../mk/files.mk

################################################################################
$(eval $(call PMADE_INSTALL_DOT,editrc))
$(eval $(call PMADE_INSTALL_DOT,lircrc))
$(eval $(call PMADE_INSTALL_DOT,festivalrc))
