#!/usr/bin/env ruby

# Rails script/server can kiss my ass, seriously, whoever fucked this
# one up needs to be kicked in the balls, I hate you.
unless $0.match(/script\/server/)

  require 'irb/completion'
  require 'irb/ext/save-history'
  ARGV << "--readline"
  IRB.conf[:PROMPT_MODE] = :SIMPLE
  IRB.conf[:AUTO_INDENT] = true
  IRB.conf[:SAVE_HISTORY] = 2000
  IRB.conf[:HISTORY_FILE] = File.expand_path("~/.irb-history")

  # start wirble (with color)
  require 'rubygems'
  require 'wirble'
  Wirble.init(:skip_prompt => true, :skip_history => true)
  Wirble.colorize

  # other libraries I like to have loaded
  require 'yaml'
  require 'open-uri'

  # nice things to have in Object for interactive use
  class Object
    def self.my_methods (sort_them=true) 
      methods = self.methods - Module.methods
      methods.sort! if sort_them
      methods
    end

    def my_methods (sort_them=true) 
      methods = self.methods - Object.methods 
      methods.sort! if sort_them
      methods
    end
  end

  # see queries in the rails console
  def arlog
    ActiveRecord::Base.logger = Logger.new(STDOUT)
    ActiveRecord::Base.clear_active_connections!
  end

end
