################################################################################
include ../mk/init.mk
include ../mk/files.mk

################################################################################
$(eval $(call PMADE_INSTALL_DOT,gitconfig))
$(eval $(call PMADE_INSTALL_DOT,gitignore))
$(eval $(call PMADE_INSTALL_DOT,mrconfig))
