#!/usr/local/bin/zsh

if [ $# -ne 1 ]; then
    echo "Usage: $0 file"
    echo "outputs all cvs tags on the given file"
    exit
fi

TMPFILE="/tmp/cvstags.sh.$$"

 cvs -q log -h $1 \
    | egrep '^[[:space:]][^:]+:' \
    | sed -E 's/^[[:space:]]//' \
    | sed -E 's/:.*$//' \
    > $TMPFILE

LINES=`wc -l $TMPFILE | awk '{print $1}'`
LESS2=`echo $LINES - 2 | bc`

head -n $LESS2 $TMPFILE
rm -f $TMPFILE
