#!zsh

#
# send your SSH public key to another host
#
if [ $# != 1 ]; then
    echo "Usage: $0 <host>"
    return 1
fi

to_host=$1
tmp=newkey

if [ -r ~/.ssh/id_dsa.pub ]; then
  src=~/.ssh/id_dsa.pub
elif [ -r ~/.ssh/id_rsa.pub ]; then
  src=~/.ssh/id_rsa.pub
else
  echo "ERROR: no public key found"
  return 1
fi

cat $src | ssh $to_host "
    mkdir -p ~/.ssh;
    chmod 700 ~/.ssh;
    cat >> ~/.ssh/authorized_keys;
    chmod 600 ~/.ssh/authorized_keys;
"
