#!zsh

#
# send your SSH public key to another host
#
if [ $# -lt 1 ]; then
    echo "Usage: $0 <host> [ssh-options]"
    return 1
fi

to_host=$1
shift

tmp=newkey
agent_key=$(ssh-add -L|awk '{print $3}'|head -1)

if [ -r "$agent_key".pub ]; then
  src="$agent_key".pub
elif [ -r ~/.ssh/id_dsa.pub ]; then
  src=~/.ssh/id_dsa.pub
elif [ -r ~/.ssh/id_rsa.pub ]; then
  src=~/.ssh/id_rsa.pub
else
  echo "ERROR: no public key found"
  return 1
fi

cat $src | ssh $@ $to_host "
    mkdir -p ~/.ssh;
    chmod 700 ~/.ssh;
    cat >> ~/.ssh/authorized_keys;
    chmod 600 ~/.ssh/authorized_keys;
"
