#!/usr/bin/env zsh

# set our editor
if which emacs > /dev/null 2>&1; then
    export EDITOR="remote-emacs-session.sh"
elif which vim > /dev/null 2>&1; then
    export EDITOR=vim
else
    export EDITOR=vi
fi

# Load a file in emacs via emacsclient, and then raise emacs
e () 
{
  remote-emacs-session.sh --eval '(elscreen-goto 3)' > /dev/null
  remote-emacs-session.sh -n $1
}
