#!/usr/bin/env zsh

# prompt magic
autoload -U colors; colors

if [[ "x$INSIDE_SCRIPT" = "x" ]]; then
    setopt prompt_percent
    setopt prompt_subst
    prompt_newline=$'\n%{\r%}'
    prompt_backtick='\`'

    precmd () 
    { 
        lc=`fc -lnD -1|awk '{print $1}'`
        PS1="%{$fg[cyan]%}.----(%{$fg[blue]%} %n%{$fg[red]%}@%{$fg[green]%}%m %{$fg[cyan]%})----(%{$fg[magenta]%} %?/$lc %{$fg[cyan]%})----%{$fg[cyan]%}(%{$fg[yellow]%} %2~ %{$fg[cyan]%})${prompt_newline}${prompt_backtick}--%{$reset_color%}> "

        if [ "x$INSIDE_EMACS" = "x" ]; then
          print -Pn "\e]0;%n@%m: %~\a"
        else
          emacs_prompt_magic
        fi
    }
else
    PS1="$ "
fi
