#!/usr/bin/env zsh

# Set default path
typeset -U path

# Add some standard directories to PATH.
[ -d ~/.cabal/bin ] && path=(~/.cabal/bin $path)

# Another tool which updates my path...
if [ -x ~/local/paths.sh ]; then
    eval $(~/local/paths.sh)
fi

# Always keep ~/bin at the head of the list.
path=(~/bin $path)

# Load SSH agent environment vars
if [ -r ~/.ssh/agent ]; then
  eval $(cat ~/.ssh/agent | egrep -v ^echo)
  export SSH_AGENT_PID
  export SSH_AUTH_SOCK
fi

# Load GPG agent environment vars
if [ -r ~/.gpg-agent-info ]; then
  source ~/.gpg-agent-info
  export GPG_AGENT_INFO
fi


# Load in optional operating system override
[ -r ~/.zsh/os ] && source ~/.zsh/os

# Load in optional local override file
[ -r ~/.zsh/local ] && source ~/.zsh/local
