#!/usr/bin/env zsh

# Set default path
typeset -U path
path=(~/bin $path)

# Load in optional operating system override
[ -r ~/.zsh/os ] && . ~/.zsh/os

# Load in optional local override file
[ -r ~/.zsh/local ] && . ~/.zsh/local
