#!/usr/local/bin/zsh

# keep some arrays unique
typeset -U fpath
typeset -U cdpath
typeset -U manpath

# some variables to export
export OSNAME=`uname -s`
export LESS="-SRiJMW"
export PAGER=less

# add our function path
functions_directory=~/.zsh/func
widgets_directory=~/.zsh/wids
fpath=($functions_directory $widgets_directory $fpath)

# clober stuff
setopt no_clobber
setopt hist_allow_clobber

# other options
setopt alwaystoend
setopt auto_cd
setopt auto_list
setopt completeinword
setopt correct
setopt magic_equal_subst
setopt mark_dirs
setopt multios
setopt no_auto_remove_slash
setopt no_beep
setopt no_correct_all
setopt rematch_pcre

# job control
setopt no_hup
setopt no_check_jobs

# autoload my functions
autoload -U ${fpath[1]}/*(:t)

# load some useful modules
zmodload zsh/datetime

# bring in other files
source ~/.zsh/lib/bindings.zsh
source ~/.zsh/lib/aliases.zsh
source ~/.zsh/lib/hosts.zsh
source ~/.zsh/lib/completion.zsh
source ~/.zsh/lib/directories.zsh
source ~/.zsh/lib/history.zsh
source ~/.zsh/lib/prompt.zsh

# Application files are autoloaded, if I can get it to freaking work:
# http://zsh.sourceforge.net/Doc/Release/Functions.html
# fpath=(~/.zsh/app $fpath)

for file in $(find ~/.zsh/app -type f -name '*.zsh'); do
  source $file
  #autoload -w $file
done
