#!/usr/local/bin/zsh

# keep some arrays unique
typeset -U fpath
typeset -U cdpath
typeset -U manpath

# some variables to export
export OSNAME=`uname -s`

# add our function path
functions_directory=~/.zsh/func
widgets_directory=~/.zsh/wids
fpath=($functions_directory $widgets_directory $fpath)

# clober stuff
setopt no_clobber 
setopt hist_allow_clobber

# other options
setopt no_beep
setopt auto_cd
setopt multios
setopt completeinword
setopt alwaystoend
setopt correct 
setopt no_correct_all
setopt magic_equal_subst

# job control
setopt no_hup
setopt no_check_jobs

# autoload my functions
autoload -U ${fpath[1]}/*(:t)

# load some useful modules
zmodload zsh/datetime

# bring in other files
source ~/.zsh/lib/bindings.zsh
source ~/.zsh/lib/aliases.zsh
source ~/.zsh/lib/hosts.zsh
source ~/.zsh/lib/completion.zsh
source ~/.zsh/lib/directories.zsh
source ~/.zsh/lib/history.zsh
source ~/.zsh/lib/prompt.zsh

for file in $(find ~/.zsh/app -type f -name '*.zsh'); do
  source $file
done
