################################################################################
# Basic settings.
directory: ~/documents/music
original_date: yes
threaded: yes
color: yes
ignore: .* *.m4p  *.m4v

################################################################################
# List of plug-ins;
plugins: >-
  bucket
  embedart
  fetchart
  ftintitle
  importadded
  missing
  mpdstats
  play
  random
  smartplaylist
  the
  types
  web

################################################################################
# Where to put music files in the library directory:
paths:
  default: "%bucket{%the{$albumartist}}/$albumartist/$album%aunique{}/$track-$title"
  singleton: "%bucket{%the{$albumartist}}/$albumartist/Non-Album/$title"
  comp: "@/$album%aunique{}/$track-$title"
  albumtype:soundtrack: "@/$album%aunique{}/$track-$title"

################################################################################
# Removing English articles.
the:
  # Remove leading quotes
  patterns: >-
    ^“ ^" ^'
################################################################################
# Sorting music into different "bucket" directories:
bucket:
  bucket_alpha: ['#', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
  bucket_alpha_regex:
    '#': ^[^A-Za-z]

################################################################################
# Music importer settings:
import:
  none_rec_action: ask
  autotag: yes
  incremental: yes
  resume: no
  log: ~/documents/ripping/beets.log

################################################################################
# MusicBrainz settings:
match:
  strong_rec_thresh: 0.10
  ignored: unmatched_tracks
  preferred:
    countries: ['US', 'GB|UK']
    media: ['CD', 'Digital Media|File']
    original_year: yes

################################################################################
# Settings for the `beet play` command:
play:
  relative_to: ~/documents/music
  command: bash -c 'cat $0 | mpc add'

################################################################################
# Settings for the types plug-in.
# http://beets.readthedocs.org/en/latest/plugins/types.html
types:
  rating: float

################################################################################
# Smart playlists.
# http://beets.readthedocs.org/en/latest/plugins/smartplaylist.html
smartplaylist:
    relative_to: ~/documents/music
    playlist_dir: ~/documents/playlists
    auto: yes

    playlists:
        - name: "Highly Rated.m3u"
          query: 'rating:0.85..'

        - name: "Recently Added.m3u"
          query: 'added:2014-06..'

        - name: "Favorite Albums.m3u"
          album_query: 'rating:1.0'
