#!/bin/sh

if [ `hostname` = 'hawkins' ]; then
  # Configure my multi-head monitors.
  xrandr --output DVI-0 --primary        --mode 1920x1080 \
         --output DVI-1 --right-of DVI-0 --mode 1920x1080

  # Share my keyboard and mouse.
  synergys -c ~/.synergy.conf --no-tray --daemon \
    --crypto-pass `cat ~/.synergy.pass` --crypto-mode gcm
fi

# Set the default cursor.
xsetroot -cursor_name left_ptr

# mlterm is a terminal emulator daemon.  Once it's started you use
# mlclient to start new X terminal emulators that share resources.
mlterm --daemon=genuine --screens=0

# Run a composition helper so I can have transparent windows.
xcompmgr -n &

# Remap my keys, but do it in the background so it doesn't conflict
# with xorg setting up the keyboard.
(sleep 8; xmodmap -pke > ~/.xmodmap.orig; xmodmap ~/.xmodmaprc) &

# Screen-saver
xscreensaver -no-splash &

# Mount my encrypted drives
if [ -r ~/etc/keys.img ]; then
  mount-keys.sh &
fi

# Add a private SSH key to the SSH agent
if [ -r ~/keys/ssh/`hostname`.id_dsa ]; then
  if ssh-add -l | grep -qv id_dsa; then
    env SSH_ASKPASS='ssh-askpass.sh' \
      ssh-add ~/keys/ssh/`hostname`.id_dsa < /dev/null &
  fi
fi

# On-screen notifications.
/usr/lib/notification-daemon/notification-daemon &

# Set my desktop background.
if [ -r $HOME/.fehbg ]; then
  sh $HOME/.fehbg &
fi

# Finally, execute my window manager.
exec $HOME/.xmonad/xmonad
