#!/bin/sh

# Set the default cursor.
xsetroot -cursor_name left_ptr

# Authentication Agents and Other Daemons.
reboot-services.sh

# Load agent environment variables.
if -r $HOME/lib/sh/agents/agent-env.sh; then
  . $HOME/lib/sh/agents/agent-env.sh
fi

# mlterm is a terminal emulator daemon.  Once it's started you use
# mlclient to start new X terminal emulators that share resources.
if ! pgrep -f 'mlterm.*daemon' 2>&1 > /dev/null; then
  mlterm --daemon=genuine --screens=0
fi

# Screen-saver
if which xscreensaver 2>&1 > /dev/null; then
  xscreensaver -no-splash &
fi

# On-screen notifications.
/usr/lib/notification-daemon/notification-daemon &

# Set my desktop background.
if [ -r $HOME/.fehbg ]; then
  sh $HOME/.fehbg &
fi

# Run any additional scripts.
if [ -d $HOME/.xinitrc.d ]; then
  for f in $HOME/.xinitrc.d/*; do
    $HOME/.xinitrc.d/$f
  done
fi

# Remap my keys, but do it in the background so it doesn't conflict
# with xorg setting up the keyboard.
(sleep 8; xmodmap -pke > ~/.xmodmap.orig; xmodmap ~/.xmodmaprc) &

# Finally, execute my window manager.
exec $HOME/bin/xmonad
