#!/bin/sh

# Set the default cursor.
xsetroot -cursor_name left_ptr

# Start dbus for everything else.
eval `dbus-launch --auto-syntax`

# Start Pulse Audio.
if which start-pulseaudio-x11 2>&1 > /dev/null; then
  if ! pgrep pulseaudio 2>&1 > /dev/null; then
    start-pulseaudio-x11
  fi
fi

# Authentication Agents and Other Daemons.
reboot-services.sh

# Load agent environment variables.
if -r $HOME/lib/sh/agents/agent-env.sh; then
  . $HOME/lib/sh/agents/agent-env.sh
fi

# urxvtd is a terminal emulator daemon.  Once it's started you use
# urxvtc to start new X terminal emulators that share resources.
if ! pgrep -f 'urxvtd' 2>&1 > /dev/null; then
  urxvtd -q -o -f
fi

# Screen-saver
if which xscreensaver 2>&1 > /dev/null; then
  xscreensaver -no-splash &
fi

# On-screen notifications.
if [ -x /usr/lib/x86_64-linux-gnu/xfce4/notifyd/xfce4-notifyd ]; then
  # First choice.
  /usr/lib/x86_64-linux-gnu/xfce4/notifyd/xfce4-notifyd &
else
  # Fallback.
  /usr/lib/notification-daemon/notification-daemon &
fi

# Set my desktop background.
if [ -r $HOME/.fehbg ]; then
  sh $HOME/.fehbg &
fi

# Run any additional scripts.
if [ -d $HOME/.xinitrc.d ]; then
  for f in $HOME/.xinitrc.d/*; do
    $f
  done
fi

# Start taffy bar.
$HOME/bin/taffybar.sh &
