################################################################################
include ../mk/init.mk
include ../mk/files.mk

################################################################################
$(eval $(call PMADE_INSTALL_DOT,tmux.conf))
$(eval $(call PMADE_INSTALL_FILE,sessions.yml,~/.tmux-sessions.yml))
$(eval $(call PMADE_INSTALL_BIN,ts,~/bin/ts))
